# Token of your Discord bot from https://discord.com/developers/applications
TOKEN = "MTE0NjU3ODUzMDcwNTA4NDUwNw.G18Xs7.ftn43h3GfE7vv4bp0cLgyd_vZGuRFuXEykgar8"

# This is the activity type of bot (status) and can be one of the following,
#   PLAYING   0
#   STREAMING 1
#   LISTENING 2
#   WATCHING  3
#   COMPETING 5
ACTIVITY_TYPE = 3

# This is the name of the activity that can be seen right next to activity type.
# You can use any text you want here.
ACTIVITY_NAME = "systems"

# Online, offline and other states bot can have. This can be one of the following,
#   online
#   idle
#   dnd
STATUS = "online"

# Guild used for slash command testing.
# This is only for development and you can safely ignore this option.
TEST_GUILD_ID = "1066351250410577960"
# Mongo URI
MONGO_URI = "mongodb://localhost:27017"

# Mongo Database name
DATABASE_NAME = "Stellar"

# If the bot is running in production mode or not. Set to "false" for testing
PRODUCTION = true